APP_MODE = "light"
COLOR_THEME = "blue"
COLOR_FONDO = "#F4F4F4"
COLOR_TEXTO = "#333333"
COLOR_TEXT_SECONDARY = "#5C6773"
COLOR_TEXT_MUTED = "#7A7A7A"
COLOR_PRIMARIO = "#007BFF"
COLOR_SECUNDARIO = "green3"
COLOR_TERCEARIO = "#FF3300"
COLOR_BLANCO = "white"
COLOR_BORDE = "#E5E5E5"
COLOR_SIDEBAR_SEPARATOR = "#D9E2EC"
MENU_BUTTON_BG = ("#F8FAFB", "#2B2B2B")
MENU_BUTTON_TEXT = "#1F2937"
MENU_HOVER_SALES = "#91D06C"
MENU_HOVER_PRODUCTS = "#FFA239"
MENU_HOVER_CLIENTS = "#5A9CB5"
MENU_HOVER_SELLERS = "#5A9CB5"
MENU_HOVER_CONSULTS = "#FFD41D"
FUENTE_TITULO = ("Segoe UI", 20, "bold")
FUENTE_NORMAL = ("Segoe UI", 13, "bold")
COLOR_SLIDE = "#EAE0CF"

# --- Unified style tokens ---
SPACING_XS = 6
SPACING_SM = 12
SPACING_MD = 20
SPACING_LG = 24

BUTTON_HEIGHT_LG = 56
BUTTON_HEIGHT_MD = 40
BUTTON_CORNER_RADIUS = 16

DISABLED_TEXT = "#9AA3AD"
DISABLED_BG = "#F1F5F9"

MENU_ACTIVE_BG = "#E8F0FF"
MENU_ACTIVE_TEXT = COLOR_PRIMARIO

ICON_SIZE_SMALL = (16, 16)
ICON_SIZE_REGULAR = (20, 20)
LOGO_SIZE = (420, 330)

# Semantic padding for pages
PAGE_PADX = SPACING_MD
PAGE_PADY = SPACING_MD
