COLOR_FONDO="#F4F4F4"
COLOR_TEXTO="#333333"
COLOR_PRIMARIO="#007BFF"
COLOR_SECUNDARIO="green3"
COLOR_TERCEARIO="#FF3300"
FUENTE_TITULO = ("Segoe UI", 20, "bold")
FUENTE_NORMAL = ("Segoe UI", 13, "bold")
COLOR_SLIDE = "#EAE0CF"
